notriddle-chocolatey-packages:
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - tmp/channel-rust-stable.toml.sha256
  before_script:
    - git remote set-url origin "https://notriddle:${CI_JOB_TOKEN}@gitlab.com/notriddle/notriddle-chocolatey-packages.git"
    - git config --global user.email michael@notriddle.com
    - git config --global user.name 'Michael "notriddle" Howell'
    - choco apikey -s "https://push.chocolatey.org/" -k="${CHOCOLATEY_TOKEN}"
    - choco install --yes --no-progress --params "/InstallDir:C:\Python3" python3
    - $env:Path = "C:\Python3;" + $env:Path
  script:
    - Write-Host "Rust"
    - cp rust/rust.nuspec rust.nuspec.bak
    - cp rust-ms/rust-ms.nuspec rust-ms.nuspec.bak
    - ./update_rust.ps1
    - if (!(Compare-Object $(cat rust.nuspec.bak) $(cat rust/rust.nuspec))) { ./push.ps1 -Confirm $False rust; git add rust; git commit -m "Bump rust version" }
    - if (!(Compare-Object $(cat rust-ms.nuspec.bak) $(cat rust-ms/rust-ms.nuspec))) { ./push.ps1 -Confirm $False rust-ms; git add rust-ms; git commit -m "Bump rust-ms version" }
    - rm rust.nuspec.bak
    - rm rust-ms.nuspec.bak
    - git status
  tags:
    - shared-windows
    - windows
